name: Build site
on:
  schedule:
    - cron: "5 5 * * *"
  push:
    branches:
      - "master"
  repository_dispatch:
    types: [update]
jobs:
  release:
    name: Build
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.x
      - run: deno run --allow-net --allow-read --allow-write --allow-run --unstable mod.ts
      - uses: maxheld83/ghpages@v0.2.1
        name: GitHub Pages Deploy
        env:
          BUILD_DIR: "public/"
          GH_PAT: ${{ secrets.GH_PAT }}
